const {chromium}=require('/opt/node22/lib/node_modules/playwright');const http=require('http'),fs=require('fs'),path=require('path');
const srv=http.createServer((q,r)=>{let f=path.join('fx',decodeURIComponent(q.url.split('?')[0]));fs.readFile(f,(e,d)=>{if(e){r.writeHead(404);return r.end();}r.writeHead(200,{'content-type':f.endsWith('.html')?'text/html; charset=utf-8':'application/javascript'});r.end(d);});}).listen(0,async()=>{
 const base='http://127.0.0.1:'+srv.address().port;const b=await chromium.launch();const pg=await b.newPage();const errs=[];pg.on('pageerror',e=>errs.push(String(e)));
 await pg.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
 await pg.addInitScript(()=>{localStorage.setItem('pk_lang','ja');localStorage.setItem('pk_svd','1');localStorage.setItem('pk_profile',JSON.stringify({name:'t',y:1990,m:6,d:8,tu:false,hh:12,mi:0,sex:'female',place:'tokyo'}));});
 await pg.goto(base+'/index.html');await pg.waitForTimeout(1000);
 const r=await pg.evaluate(()=>{const o=[];const S=(l,t)=>{state.lang=l;return _softenJargon(t);};
  o.push(['zh 十年运势',S('zh','进入一个新的十年运势阶段。')]);
  o.push(['zh 大运',S('zh','你的大运很好。')]);
  o.push(['zh 大运势',S('zh','今年的大运势不错。')]);
  o.push(['zt 十年運勢',S('zt','這個十年運勢的轉換')]);
  o.push(['ko 과정인',S('ko','알짜배기 재료를 모아가는 과정인 셈이죠.')]);
  o.push(['ko 정인',S('ko','정인이 들어와요.')]);
  const W=(l,t)=>{state.lang=l;return _wrongLang(t);};
  o.push(['wrong zt(日本語)',W('zt','Nicoです。あなたの星を読みました。')]);
  o.push(['wrong zt(正常)',W('zt','你好，我是Nico。')]);
  o.push(['wrong pt(漢字混入)',W('pt','Eu sou a Nico, sua 鑑定師 pessoal.')]);
  o.push(['wrong pt(正常)',W('pt','Eu sou a Nico, sua leitora pessoal.')]);
  o.push(['wrong en(括弧注記のみ)',W('en','Your decade (大運) is strong.')]);
  o.push(['wrong ja(正常)',W('ja','こんにちは')]);
  o.push(['wrong ko(正常)',W('ko','안녕하세요')]);
  o.push(['wrong th(正常)',W('th','สวัสดีค่ะ')]);
  o.push(['wrong ja(ベトナム語の文字が混入)',W('ja','貯金を全部使うとなると、慎ướngも必要だと感じます。')]);
  o.push(['wrong pt(正常・â ê ô)',W('pt','Você está ótima, que bênção, avô.')]);
  o.push(['wrong vi(正常)',W('vi','Chào buổi sáng, bạn ăn sáng chưa?')]);
  o.push(['wrong en(タイ文字が混入)',W('en','Have a nice day ครับ')]);
  const V=q=>RE_VALIDATE.test(q);
  o.push(['肯定してほしい（該当）',[V('明日会社辞めて、貯金全部使ってカフェ開こうと思う！絶対うまくいくよね？'),V('彼氏がLINEを3時間返さなかったから、別れるって言ってブロックした。私悪くないよね？'),V("I'm quitting my job tomorrow and putting all my savings into opening a café!"),V("I'm not wrong, am I?"),V('나 잘못한 거 없지?'),V('¡Mañana dejo mi trabajo!'),V('No hice nada malo, ¿verdad?'),V('我没错吧？'),V('Aku gak salah kan?'),V('ไม่ผิดใช่ไหม'),V('Tôi không sai đúng không?'),V('Eu não errei, né?')].join()]);
  o.push(['肯定してほしい（該当しない）',[V('今日暑いね'),V('おはよう'),V('ありがとう！'),V('明日も仕事かー'),V("It's cold today, right?"),V('오늘 날씨 좋지?'),V('Hace calor, ¿verdad?'),V('今年の恋愛運は？')].join()]);
  o.push(['上位モデルへ（自分責め・寝ていない・欠点）',[RE_HEAVY.test('何やってもうまくいかない。私ってダメな人間なのかな'),RE_HEAVY.test("Overtime again all this week, barely slept."),RE_HEAVY.test('잠을 못 잤어'),RE_HEAVY.test('No he dormido nada'),RE_DECISION.test('正直に言って、私の性格の欠点って何？'),RE_DECISION.test('What are my flaws?'),RE_DECISION.test('내 단점이 뭐야?')].join()]);
  o.push(['上位モデルへ（該当しない）',[RE_HEAVY.test('今日はよく寝た！'),RE_HEAVY.test('I slept well'),RE_DECISION.test('今日の運勢は？'),RE_HEAVY.test('お昼何食べよう')].join()]);
  o.push(['ニコの性別の質問',['ニコって男の子？女の子？','Nico, are you a boy or a girl?','Nico你是男生還是女生？','니코는 남자야 여자야?','Nico là con trai hay con gái vậy?','Nico, ¿eres chico o chica?','Nico, você é menino ou menina?','Nico itu cowok atau cewek?','Nico เป็นผู้ชายหรือผู้หญิง?'].map(q=>RE_NICO_SELF.test(q)).join()]);
  state.lang='ja';
  o.push(['十二運の漏れ',_finalTidy('粘り強さ（の病）と、集中力（育ちの土台の堅実さ・死）の賜物。持病（持病）は（病院）へ。')]);
  window._pendingChips=null; state.lang='zh';
  o.push(['chips zh', _extractChips('更深层次的东西。 ["今年有恋爱运吗？" / "工作上会有新机会？" / "今年能顺利吗？"]'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='pt';
  o.push(['chips pt', _extractChips('de forma mais direta. "Qual o meu período atual? " / "Quais talentos eu tenho? " / "Como será o futuro? "'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='th';
  o.push(['chips th改行', _extractChips('ข้อความ "อยากรู้เรื่องช่วงสร้างฐานะ? " / "มีอะไรเกี่ยวกับช่วงเตรียมตัว?\n" / "ช่วงชีวิตนี้มีจุดเปลี่ยน? "'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='th';
  o.push(['chips th改行区切り', _extractChips('ข้อความ ค่ะ "อยากรู้เรื่องงาน?"\n"แล้วชีวิตช่วงต่อไปเป็นไง? "'), JSON.stringify(window._pendingChips)]);
  state.lang='zh'; o.push(['zh 你们的你的特质', _finalTidy('从你们的你的特质来看，你的你的特质很好')]); state.lang='zt'; o.push(['zt 妳和他的你的特質', _finalTidy('從妳和他的你的特質來看')]);
  { const P='Trong lá số của bạn, có một giai đoạn đặc biệt mà bạn có thể thu hút được sự chú ý của người khác, giống như những cánh hoa đào nở rộ trong tình yêu vậy. Điều này sẽ diễn ra rõ nét hơn vào khoảng năm 2027.';
    const bak=state.msgs; state.msgs=[{role:'ai',text:P}]; state.lang='vi';
    o.push(['段落の写し', _dropRepeatedParas('Nhược điểm của bạn là đôi khi hơi thiếu quyết đoán khi gặp áp lực, và dễ để ý kiến người khác ảnh hưởng.\n\n'+P+'\n\nHãy chăm sóc bản thân nhé, mỗi ngày một chút thôi cũng được, bạn nhé.')]); state.msgs=bak; }
  state.lang='ko'; o.push(['ko 별자리', _finalTidy('당신의 별자리를 읽고, 별자리가 빛나요')]);
  window._pendingChips=null; state.lang='zh'; o.push(['chips zh改行', _extractChips('迎来新的发展机遇。 ["接下来的十年运势如何？ "\n"我什么时候会迎来转折？ "\n"我现在稳步发展的原因？ "]'), JSON.stringify(window._pendingChips)]);
  state.lang='ko'; o.push(['ko 님', _finalTidy('님, 안녕하세요! 저는 Nico예요.'), _finalTidy('지수님, 안녕하세요')]);
  state.lang='th'; o.push(['th ,,', _finalTidy('ดีมาก,, และสบาย,,')]);
  o.push(['BE th', _jargonLeak('ต้นปี 2578 ค่ะ',false), _jargonLeak('ปี 2035 ค่ะ',false)]);
  state.lang='zh'; o.push(['zh 害', _jargonLeak('有一个“害”与你月份的“未”',false), _jargonLeak('有一个“害”',true), _jargonLeak('你好，我是Nico',false)]);
  window._pendingChips=null;
  o.push(['chips 通常の引用は残す', _extractChips('彼は「ありがとう」と言いました。')]);
  return o;});
 r.forEach(x=>console.log(x.join(' => '))); console.log('errors',errs);
 await b.close();srv.close();});
