const {chromium}=require('/opt/node22/lib/node_modules/playwright');const http=require('http'),fs=require('fs'),path=require('path');
const srv=http.createServer((q,r)=>{let f=path.join('fx',decodeURIComponent(q.url.split('?')[0]));fs.readFile(f,(e,d)=>{if(e){r.writeHead(404);return r.end();}r.writeHead(200,{'content-type':f.endsWith('.html')?'text/html; charset=utf-8':'application/javascript'});r.end(d);});}).listen(0,async()=>{
 const base='http://127.0.0.1:'+srv.address().port;const b=await chromium.launch();const pg=await b.newPage();const errs=[];pg.on('pageerror',e=>errs.push(String(e)));
 await pg.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
 await pg.addInitScript(()=>{localStorage.setItem('pk_lang','ja');localStorage.setItem('pk_svd','1');localStorage.setItem('pk_profile',JSON.stringify({name:'t',y:1990,m:6,d:8,tu:false,hh:12,mi:0,sex:'female',place:'tokyo'}));});
 await pg.goto(base+'/index.html');await pg.waitForTimeout(1000);
 const r=await pg.evaluate(()=>{const o=[];const S=(l,t)=>{state.lang=l;return _softenJargon(t);};
  o.push(['zh 十年运势',S('zh','进入一个新的十年运势阶段。')]);
  o.push(['zh 大运',S('zh','你的大运很好。')]);
  o.push(['zh 大运势',S('zh','今年的大运势不错。')]);
  o.push(['zt 十年運勢',S('zt','這個十年運勢的轉換')]);
  o.push(['ko 과정인',S('ko','알짜배기 재료를 모아가는 과정인 셈이죠.')]);
  o.push(['ko 정인',S('ko','정인이 들어와요.')]);
  const W=(l,t)=>{state.lang=l;return _wrongLang(t);};
  o.push(['wrong zt(日本語)',W('zt','Nicoです。あなたの星を読みました。')]);
  o.push(['wrong zt(正常)',W('zt','你好，我是Nico。')]);
  o.push(['wrong pt(漢字混入)',W('pt','Eu sou a Nico, sua 鑑定師 pessoal.')]);
  o.push(['wrong pt(正常)',W('pt','Eu sou a Nico, sua leitora pessoal.')]);
  o.push(['wrong en(括弧注記のみ)',W('en','Your decade (大運) is strong.')]);
  o.push(['wrong ja(正常)',W('ja','こんにちは')]);
  o.push(['wrong ko(正常)',W('ko','안녕하세요')]);
  o.push(['wrong th(正常)',W('th','สวัสดีค่ะ')]);
  o.push(['wrong ja(ベトナム語の文字が混入)',W('ja','貯金を全部使うとなると、慎ướngも必要だと感じます。')]);
  o.push(['wrong pt(正常・â ê ô)',W('pt','Você está ótima, que bênção, avô.')]);
  o.push(['wrong vi(正常)',W('vi','Chào buổi sáng, bạn ăn sáng chưa?')]);
  o.push(['wrong en(タイ文字が混入)',W('en','Have a nice day ครับ')]);
  const V=q=>RE_VALIDATE.test(q);
  o.push(['肯定してほしい（該当）',[V('明日会社辞めて、貯金全部使ってカフェ開こうと思う！絶対うまくいくよね？'),V('彼氏がLINEを3時間返さなかったから、別れるって言ってブロックした。私悪くないよね？'),V("I'm quitting my job tomorrow and putting all my savings into opening a café!"),V("I'm not wrong, am I?"),V('나 잘못한 거 없지?'),V('¡Mañana dejo mi trabajo!'),V('No hice nada malo, ¿verdad?'),V('我没错吧？'),V('Aku gak salah kan?'),V('ไม่ผิดใช่ไหม'),V('Tôi không sai đúng không?'),V('Eu não errei, né?')].join()]);
  o.push(['肯定してほしい（該当しない）',[V('今日暑いね'),V('おはよう'),V('ありがとう！'),V('明日も仕事かー'),V("It's cold today, right?"),V('오늘 날씨 좋지?'),V('Hace calor, ¿verdad?'),V('今年の恋愛運は？')].join()]);
  o.push(['上位モデルへ（自分責め・寝ていない・欠点）',[RE_HEAVY.test('何やってもうまくいかない。私ってダメな人間なのかな'),RE_HEAVY.test("Overtime again all this week, barely slept."),RE_HEAVY.test('잠을 못 잤어'),RE_HEAVY.test('No he dormido nada'),RE_DECISION.test('正直に言って、私の性格の欠点って何？'),RE_DECISION.test('What are my flaws?'),RE_DECISION.test('내 단점이 뭐야?')].join()]);
  o.push(['上位モデルへ（該当しない）',[RE_HEAVY.test('今日はよく寝た！'),RE_HEAVY.test('I slept well'),RE_DECISION.test('今日の運勢は？'),RE_HEAVY.test('お昼何食べよう')].join()]);
  o.push(['ニコの性別の質問',['ニコって男の子？女の子？','Nico, are you a boy or a girl?','Nico你是男生還是女生？','니코는 남자야 여자야?','Nico là con trai hay con gái vậy?','Nico, ¿eres chico o chica?','Nico, você é menino ou menina?','Nico itu cowok atau cewek?','Nico เป็นผู้ชายหรือผู้หญิง?'].map(q=>RE_NICO_SELF.test(q)).join()]);
  o.push(['辞めちゃっていいよね型',[RE_VALIDATE.test('でも正直、今の上司が嫌いなだけかも。すぐ辞めちゃっていいよね？'),RE_VALIDATE.test("Is it okay to just quit?"),RE_VALIDATE.test('그만둬도 되겠지?'),RE_VALIDATE.test('私悪くないよね？'),RE_VALIDATE.test('今日はいい天気だよね？')].join()]);
  o.push(['理由を聞く（該当）',['なんでそう言えるの？','なぜ？','どうしてそう思うの？','Why do you say that?','为什么这么说？','왜 그렇게 말해?'].map(q=>RE_THEORY.test(q)).join()]);
  o.push(['理由を聞く（該当しない）',['なんで雨なんだろう','今日なにしよう','Why not!'].map(q=>RE_THEORY.test(q)).join()]);
  o.push(['専門用語を頼んだ時だけ用語',[RE_JARGON_OK.test('専門用語で詳しく説明して'),RE_JARGON_OK.test('Explain it in technical terms'),RE_JARGON_OK.test('なんでそう言えるの？'),RE_JARGON_OK.test('Why do you say that?'),whyNote('なんでそう言えるの？').indexOf('PLAIN-EVIDENCE')>0,whyNote('専門用語で詳しく説明して').indexOf('TECHNICAL TERMS REQUESTED')>0,whyNote('今日の運勢は？')===''].join()]);
  o.push(['恋の結果を聞く（該当）',['彼とまたやり直せる？','Will he come back?',"I'm 40 and still single. Will I ever find someone?",'재회할 수 있을까?','我们还有可能复合吗？','เราจะกลับมาคืนดีกันได้ไหม','Apa dia juga suka aku?','¿Volverá conmigo?','Será que ele volta pra mim?'].map(q=>RE_LOVE_OUTCOME.test(q)).join()]);
  o.push(['恋の結果を聞く（該当しない）',['今日の運勢は？','仕事が忙しい','How is my career this year?'].map(q=>RE_LOVE_OUTCOME.test(q)).join()]);
  o.push(['つらい言葉の段階',(function(){ state.lang='ja'; state.msgs=[{role:'me',text:'最近うまくいかない'},{role:'me',text:'何のために生きてるのかわからない'}];
    var a=_shLevel('何のために生きてるのかわからない'), r=_ensureHelpline('何のために生きてるのかわからない',{text:'つらいね。ここにいるよ。'});
    state.msgs.push({role:'me',text:'もう限界'}); var b=_shLevel('もう限界'), r2=_ensureHelpline('もう限界',{text:'ここにいるよ。'});
    state.msgs=[{role:'me',text:'もう死にたい'}]; var c=_shLevel('もう死にたい'), r3=_ensureHelpline('もう死にたい',{text:'ここにいるよ。'});
    var r4=_ensureHelpline('今日の運勢は？',{text:'いい日だよ。'}); state.msgs=[];
    return [a, r.text.indexOf(pick(HELPLINE))<0, b, r2.text.indexOf(pick(HELPLINE))>=0, c, r3.text.indexOf(pick(HELPLINE))>=0, r4.text==='いい日だよ。'].join(); })()]);
  window._aiTopicHint=null; state.msgs=[];
  o.push(['恋愛の定番を恋愛と見分ける（AI分類なし）',['彼と結婚したいけど迷ってる','元彼とよりを戻したい','同じ職場の女の子を好きになった。私も女です','既婚者の彼を奪いたい','My boyfriend wants to marry me','I want to get back with my ex','I am gay and scared to come out','我想和前任复合','남자친구랑 결혼해도 될까','Tôi là người đồng tính','Quero voltar com meu ex','Aku mau nikah tapi ragu','อยากคืนดีกับแฟนเก่า'].map(q=>_effectiveTopic(q)).join()]);
  o.push(['家族の話は恋愛にしない',['姉が結婚する','My parents are getting a divorce'].map(q=>_effectiveTopic(q)).join()]);
  o.push(['種類の見分け',[RE_LOVE_MARRIAGE.test('プロポーズされた'),RE_LOVE_REUNION.test('復縁したい'),RE_LOVE_LGBT.test('彼女が好き。私も女性です'),RE_LOVE_LGBT.test('同性の先輩が好き'),RE_LOVE_LGBT.test('나 게이야')].join()]);
  o.push(['恋人の浮気',['彼女が浮気してるかもしれない','남편이 바람피우는 것 같아','Descubrí que mi esposo me engaña','แฟนมีคนอื่น','I think my husband is cheating','我老公出轨了','彼が好き'].map(q=>RE_PARTNER_CHEAT.test(q)).join()]);
  o.push(['送る文面の〇〇は残す',(function(){ state.lang='ja'; return _softenJargon('「久しぶり！〇〇のことで教えてほしくて」と送る。〇〇さんは'); })()]);
  o.push(['深い悩みの決まり文句を除く',(function(){ state.lang='ja'; state.msgs=[]; try{localStorage.setItem('pk_ctxs','0');}catch(e){}
    var r=_dropFiller('不安で全然眠れない',{text:'眠れないほど不安なのですね。最後に彼と話した言葉が、ずっと頭に残っていませんか？今夜は温かいお茶を飲んで、早めに休んでくださいね。'}).text;
    var r2=_dropFiller('眠れるコツを教えて',{text:'寝る前に深呼吸をしてみてね。'}).text;
    var r3=_dropFiller('今日の運勢は？',{text:'今日はお茶でも飲んでのんびりしよう。'}).text;
    state.lang='en'; var r4=_dropFiller('He broke up with me last night',{text:'I am so sorry. What did he say when he ended it? Maybe have a warm drink and get some rest tonight.'}).text; state.lang='ja';
    return [r, r2, r3, r4].join(' | '); })()]);
  o.push(['性格の説明の繰り返しを止める',(function(){ state.msgs=[{role:'me',text:'a'},{role:'ai',text:'さきさんはもともと細やかな気配りができる方です。'}]; var a=natureNote().indexOf('NO PERSONALITY')>0; state.msgs=[{role:'me',text:'a'},{role:'ai',text:'最後に送ったLINEを教えて？'}]; var b=natureNote()===''; state.msgs=[]; return [a,b].join(); })()]);
  state.lang='ja';
  o.push(['読みがなの残り',_finalTidy('探究心（たいきょくきじん・物事を深く追究する星）と、まじめさ（せいかん）。生まれ持った星の組み合わせ（生まれ持った星）です。お上司が嫌い。')]);
  state.lang='ja';
  o.push(['十二運の漏れ',_finalTidy('粘り強さ（の病）と、集中力（育ちの土台の堅実さ・死）の賜物。持病（持病）は（病院）へ。')]);
  window._pendingChips=null; state.lang='zh';
  o.push(['chips zh', _extractChips('更深层次的东西。 ["今年有恋爱运吗？" / "工作上会有新机会？" / "今年能顺利吗？"]'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='pt';
  o.push(['chips pt', _extractChips('de forma mais direta. "Qual o meu período atual? " / "Quais talentos eu tenho? " / "Como será o futuro? "'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='th';
  o.push(['chips th改行', _extractChips('ข้อความ "อยากรู้เรื่องช่วงสร้างฐานะ? " / "มีอะไรเกี่ยวกับช่วงเตรียมตัว?\n" / "ช่วงชีวิตนี้มีจุดเปลี่ยน? "'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='th';
  o.push(['chips th改行区切り', _extractChips('ข้อความ ค่ะ "อยากรู้เรื่องงาน?"\n"แล้วชีวิตช่วงต่อไปเป็นไง? "'), JSON.stringify(window._pendingChips)]);
  state.lang='zh'; o.push(['zh 你们的你的特质', _finalTidy('从你们的你的特质来看，你的你的特质很好')]); state.lang='zt'; o.push(['zt 妳和他的你的特質', _finalTidy('從妳和他的你的特質來看')]);
  { const P='Trong lá số của bạn, có một giai đoạn đặc biệt mà bạn có thể thu hút được sự chú ý của người khác, giống như những cánh hoa đào nở rộ trong tình yêu vậy. Điều này sẽ diễn ra rõ nét hơn vào khoảng năm 2027.';
    const bak=state.msgs; state.msgs=[{role:'ai',text:P}]; state.lang='vi';
    o.push(['段落の写し', _dropRepeatedParas('Nhược điểm của bạn là đôi khi hơi thiếu quyết đoán khi gặp áp lực, và dễ để ý kiến người khác ảnh hưởng.\n\n'+P+'\n\nHãy chăm sóc bản thân nhé, mỗi ngày một chút thôi cũng được, bạn nhé.')]); state.msgs=bak; }
  state.lang='ko'; o.push(['ko 별자리', _finalTidy('당신의 별자리를 읽고, 별자리가 빛나요')]);
  window._pendingChips=null; state.lang='zh'; o.push(['chips zh改行', _extractChips('迎来新的发展机遇。 ["接下来的十年运势如何？ "\n"我什么时候会迎来转折？ "\n"我现在稳步发展的原因？ "]'), JSON.stringify(window._pendingChips)]);
  state.lang='ko'; o.push(['ko 님', _finalTidy('님, 안녕하세요! 저는 Nico예요.'), _finalTidy('지수님, 안녕하세요')]);
  state.lang='th'; o.push(['th ,,', _finalTidy('ดีมาก,, และสบาย,,')]);
  o.push(['BE th', _jargonLeak('ต้นปี 2578 ค่ะ',false), _jargonLeak('ปี 2035 ค่ะ',false)]);
  state.lang='zh'; o.push(['zh 害', _jargonLeak('有一个“害”与你月份的“未”',false), _jargonLeak('有一个“害”',true), _jargonLeak('你好，我是Nico',false)]);
  window._pendingChips=null;
  o.push(['chips 通常の引用は残す', _extractChips('彼は「ありがとう」と言いました。')]);
  return o;});
 r.forEach(x=>console.log(x.join(' => '))); console.log('errors',errs);
 await b.close();srv.close();});
