const {chromium}=require('/opt/node22/lib/node_modules/playwright');const http=require('http'),fs=require('fs'),path=require('path');
const srv=http.createServer((q,r)=>{let f=path.join('fx',decodeURIComponent(q.url.split('?')[0]));fs.readFile(f,(e,d)=>{if(e){r.writeHead(404);return r.end();}r.writeHead(200,{'content-type':f.endsWith('.html')?'text/html; charset=utf-8':'application/javascript'});r.end(d);});}).listen(0,async()=>{
 const base='http://127.0.0.1:'+srv.address().port;const b=await chromium.launch();const pg=await b.newPage();const errs=[];pg.on('pageerror',e=>errs.push(String(e)));
 await pg.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
 await pg.addInitScript(()=>{localStorage.setItem('pk_lang','ja');localStorage.setItem('pk_svd','1');localStorage.setItem('pk_profile',JSON.stringify({name:'t',y:1990,m:6,d:8,tu:false,hh:12,mi:0,sex:'female',place:'tokyo'}));});
 await pg.goto(base+'/index.html');await pg.waitForTimeout(1000);
 const r=await pg.evaluate(()=>{const o=[];const S=(l,t)=>{state.lang=l;return _softenJargon(t);};
  o.push(['zh 十年运势',S('zh','进入一个新的十年运势阶段。')]);
  o.push(['zh 大运',S('zh','你的大运很好。')]);
  o.push(['zh 大运势',S('zh','今年的大运势不错。')]);
  o.push(['zt 十年運勢',S('zt','這個十年運勢的轉換')]);
  o.push(['ko 과정인',S('ko','알짜배기 재료를 모아가는 과정인 셈이죠.')]);
  o.push(['ko 정인',S('ko','정인이 들어와요.')]);
  const W=(l,t)=>{state.lang=l;return _wrongLang(t);};
  o.push(['wrong zt(日本語)',W('zt','Nicoです。あなたの星を読みました。')]);
  o.push(['wrong zt(正常)',W('zt','你好，我是Nico。')]);
  o.push(['wrong pt(漢字混入)',W('pt','Eu sou a Nico, sua 鑑定師 pessoal.')]);
  o.push(['wrong pt(正常)',W('pt','Eu sou a Nico, sua leitora pessoal.')]);
  o.push(['wrong en(括弧注記のみ)',W('en','Your decade (大運) is strong.')]);
  o.push(['wrong ja(正常)',W('ja','こんにちは')]);
  o.push(['wrong ko(正常)',W('ko','안녕하세요')]);
  o.push(['wrong th(正常)',W('th','สวัสดีค่ะ')]);
  window._pendingChips=null; state.lang='zh';
  o.push(['chips zh', _extractChips('更深层次的东西。 ["今年有恋爱运吗？" / "工作上会有新机会？" / "今年能顺利吗？"]'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='pt';
  o.push(['chips pt', _extractChips('de forma mais direta. "Qual o meu período atual? " / "Quais talentos eu tenho? " / "Como será o futuro? "'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='th';
  o.push(['chips th改行', _extractChips('ข้อความ "อยากรู้เรื่องช่วงสร้างฐานะ? " / "มีอะไรเกี่ยวกับช่วงเตรียมตัว?\n" / "ช่วงชีวิตนี้มีจุดเปลี่ยน? "'), JSON.stringify(window._pendingChips)]);
  window._pendingChips=null; state.lang='th';
  o.push(['chips th改行区切り', _extractChips('ข้อความ ค่ะ "อยากรู้เรื่องงาน?"\n"แล้วชีวิตช่วงต่อไปเป็นไง? "'), JSON.stringify(window._pendingChips)]);
  state.lang='ko'; o.push(['ko 별자리', _finalTidy('당신의 별자리를 읽고, 별자리가 빛나요')]);
  window._pendingChips=null; state.lang='zh'; o.push(['chips zh改行', _extractChips('迎来新的发展机遇。 ["接下来的十年运势如何？ "\n"我什么时候会迎来转折？ "\n"我现在稳步发展的原因？ "]'), JSON.stringify(window._pendingChips)]);
  state.lang='ko'; o.push(['ko 님', _finalTidy('님, 안녕하세요! 저는 Nico예요.'), _finalTidy('지수님, 안녕하세요')]);
  state.lang='th'; o.push(['th ,,', _finalTidy('ดีมาก,, และสบาย,,')]);
  o.push(['BE th', _jargonLeak('ต้นปี 2578 ค่ะ',false), _jargonLeak('ปี 2035 ค่ะ',false)]);
  state.lang='zh'; o.push(['zh 害', _jargonLeak('有一个“害”与你月份的“未”',false), _jargonLeak('有一个“害”',true), _jargonLeak('你好，我是Nico',false)]);
  window._pendingChips=null;
  o.push(['chips 通常の引用は残す', _extractChips('彼は「ありがとう」と言いました。')]);
  return o;});
 r.forEach(x=>console.log(x.join(' => '))); console.log('errors',errs);
 await b.close();srv.close();});
